title: My blog
author: me
email: me@domain.com
description: > # this means to ignore newlines until "baseurl:"
 this is an awesome descrition of my blog

# social links
twitter_username: eallatta
github_username:  MrAllatta

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
